---
deployment:
  tasks:
    - echo "Deployment triggered" > /home/username/public_html/test_deployment.txt
    - export DEPLOYPATH=/home/faithhil/public_html/
    - /bin/cp -R wp-content $DEPLOYPATH
    - /bin/cp -R wp-includes $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R about.html $DEPLOYPATH
    - /bin/cp -R contact.html $DEPLOYPATH
    - /bin/cp -R services.html $DEPLOYPATH
